apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.app.name }}-deployment
  namespace: {{ .Values.argo.namespace }}
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: https://kubernetes.default.svc
  project: {{ .Values.argo.project }}
  source:
    helm:
      parameters:
      - name: app.name
        value: {{ .Values.app.name }}
    path: deployment
    repoURL: https://github.com/Jaland/argo-tekton-flow.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
