apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.app.name }}-pipeline
  namespace: {{ .Values.argo.namespace }}
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: https://kubernetes.default.svc
  project: {{ .Values.argo.project }}
  source:
    helm:
      parameters:
      - name: app.name
        value: {{ .Values.app.name }}
      - name: argo.project
        value: {{ .Values.argo.project }}
      - name: argo.application
        value: {{ .Values.app.name }}-deployment
        
    path: tekton
    repoURL: https://github.com/jland-redhat/argo-tekton-flow-git-only.git
    targetRevision: HEAD
  # Turn on automated Syncing
  syncPolicy:
    automated:
      selfHeal: true